version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  api:
    build: .
    ports:
      - "4000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:8819@db:5432/burger

