import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@src/styles/Home.module.css'
import { Header } from '@src/components/Header'
import styled from "styled-components";
import { Main } from '@src/components/Main';
import { useState } from 'react';


export default function Home() {

  const [search, setSearch] = useState('');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="">

        
        <Header setSearch={setSearch} />
        <Main />

      </div>
    </>
  )
}
