import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@src/styles/Home.module.css'
import { Header } from '@src/components/Header'
import styled from "styled-components";
import { Main } from '@src/components/Main';
import { useEffect, useState } from 'react';
import { Product } from './../interfaces/Product';
import { useQuery } from 'react-query'
import { getProducts } from './../services/api/index';


export default function Home() {

  const [search, setSearch] = useState('');
  const {data, isLoading} = useQuery<Product[]>(["products"], 
    () => getProducts()
  );

  useEffect(() => {
    console.log(data)
  }, [data])
  

  return (
    <>
      <Head>
        <title>Burger Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="">

        
        <Header setSearch={setSearch} />
        {!isLoading && data &&
          <Main data={data} />
        }

      </div>
    </>
  )
}
